server.port=8080

spring.application.name=api-gateway

spring.cloud.gateway.routes[0].id=cinema-core-service
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/films/**,/api/salons/**,/api/seanslar/**

spring.cloud.gateway.routes[1].id=cinema-booking-service
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/auth/**,/api/rezervasyonlar/**,/api/biletler/**cd